#!/usr/bin/env bash

MAP_DIR="../qwe/mapping"
NAV_DIR="../qwe/navigation"

# Only rebuild binary map if it doesn't exist and redo param is not given
if [ "$1" != "redo" ]
then
  if [ -f $NAV_DIR/maps/binary_map.txt ]
  then
    echo "Map already exists. Give \"redo\" as param to generate a new one."
    exit 0
  fi
fi

if [ $# -ne 2 ]
then
  cells_per_inch=4
else
  cells_per_inch=$2
fi

# Unpickle map and generate map_desc.txt (map in text file)
(cd $MAP_DIR && python map_script.py -r $cells_per_inch)

# Confirm that map text file was created
if [ ! -f $MAP_DIR/map_desc.txt ]
then
  echo "Error: map_desc.txt was not generated by map_script.py"
  exit 1
fi

# Translate things I can drive on to 0, things I can't to 1 and commas to spaces
cat $MAP_DIR/map_desc.txt | tr "17" "0" | tr "2345689" "1" | tr "," " " > $NAV_DIR/maps/binary_map.txt
